### ISSUE TITLE
build_runner watch não funciona no Windows e Linux

### ISSUE THREAD

**Issue by israelhudson** [Flutterando/flutter_mobx_extension#5]
Quando usei o projeto no Mac OS a função de build_runner watch funcionou perfeitamente porem no linux e windows não funciona. 

É possível que em futuras versões seja possível editar o comando que a extensão executa?

**Comment by davidsdearaujo** [comment]
No windows funcionou tranquilo aqui...
Mas eu preciso dar um `flutter pub get` as vezes.

Qual o erro que está dando pra você?

**Comment by israelhudson** [comment]
> No windows funcionou tranquilo aqui...
> Mas eu preciso dar um `flutter pub get` as vezes.
> 
> Qual o erro que está dando pra você?

percebi aqui que em um projeto novo está dando certo na windows e linux tambem porem o projeto que eu estava tentando ele pedia um --polling junto com o comando do build runner. Seria bem bacana o plugin deixar o dev escolher as flags.

**Comment by jacobaraujo7** [comment]
vou criar um json configuration
